# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="AldrovandiLab",
		root=root,
		repositoryPath="repositories/AldrovandiLab",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="AldrovandiLab.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;