# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="AldrovandiLabUCLA",
		root=root,
		repositoryPath="repositories/AldrovandiLabUCLA",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="AldrovandiLabUCLA.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;