# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="KINETICS_MANUSCRIPT",
		root=root,
		repositoryPath="repositories/KINETICS_MANUSCRIPT",
		sheetFormat="xlsx",
		databasePath="databases",
		databaseFile="KINETICS_MANUSCRIPT.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;