# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="LabData",
		root=root,
		repositoryPath="repositories/LabData",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="LabData.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;