# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="myLabbook",
		root=root,
		repositoryPath="repositories/myLabbook",
		sheetFormat="xlsx",
		databasePath="databases",
		databaseFile="myLabbook.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;