# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="NewLabbook",
		root=root,
		repositoryPath="repositories/NewLabbook",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="NewLabbook.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;