# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="newxfr",
		root=root,
		repositoryPath="repositories/newxfr",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="newxfr.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;