# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="test2",
		root=root,
		repositoryPath="repositories/test2",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="test2.SQLITE3",
		databaseFormat="SQLITE3",
	);
	return plb;