# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="UCLALab",
		root=root,
		repositoryPath="repositories/UCLALab",
		sheetFormat="csv",
		databasePath="databases",
		databaseFile="UCLALab.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;