# pyLabbook specification generated by pyLabbook.py
from pyLabbook import pyLabbook;
def initialize(root):
	plb = pyLabbook(
		id="ucla",
		root=root,
		repositoryPath="repositories/ucla",
		sheetFormat="xlsx",
		databasePath="databases",
		databaseFile="ucla.sqlite3",
		databaseFormat="SQLITE3",
	);
	return plb;