# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
    def setup(s):
        s.PROTOCOLID = "inhibitorVersion2";
        s.addSetColumn(
            name          = "subject",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "subject name",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "inhibitor",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "inhibitor name",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "max_concentration",
            type          = "REAL",
            notnull       = True,
            unique        = False,
            description   = "max concentration of inhibitor in titration series",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "type",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "sample type",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "dilution_id",
            type          = "INTEGER",
            notnull       = True,
            unique        = False,
            description   = "position in titration series",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "value",
            type          = "TEXT",
            notnull       = False,
            unique        = False,
            description   = "measured infectivity value",
            default       = None,
            primary_key   = False,
        );