# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
	def setup(s):
		s.PROTOCOLID = "MASSXFR24W";
		s.addSetColumn(
			name			= "SOURCE_FILE_PATH",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "path to raw data file",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "SOURCE_FILE_NAME",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of raw data file",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "SOURCE_FILE_SHEET",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "raw data sheet",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "PLATEMAP",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of platemap used for data extraction",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "ENV_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name or id of env being pseudotyped",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "ENV_TUBE_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "plasmid tube id of env",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "ENV_TUBE_CONC",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "concentration of env plasmid",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "ENV_TUBE_CONC_UNITS",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "concentration units for env plasmid",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "BB_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of backbone plasmid",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "BB_TUBE_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "tube id of backbone plasmid",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "BB_TUBE_CONC",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "concentration of backbone plasmid",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "BB_TUBE_CONC_UNITS",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "units of backbone plasmid concentration",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "REPORTER",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of infectivity reporter",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "READ_TYPE",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "infectivity read type",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "RECIPE_ID",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "id code for transfection recipe",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "NOTES",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "notes",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "PLATE_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "id of plate",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "WELL_ID",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "id of well",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "DILUTION_ID",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "supernatant dilution id for inoculation",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "VALUE",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "measured infectivity value",
			default			= None,
			primary_key		= False,
		);
