# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
    def setup(s):
        s.PROTOCOLID = "myProtocol";
        s.addSetColumn(
            name          = "sample",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "sample",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "inhibitor",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "inhibitor",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "max_conc",
            type          = "REAL",
            notnull       = True,
            unique        = False,
            description   = "max_conc",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "notes",
            type          = "TEXT",
            notnull       = False,
            unique        = False,
            description   = "notes",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "type",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "sample type",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "value",
            type          = "TEXT",
            notnull       = False,
            unique        = False,
            description   = "measured value",
            default       = None,
            primary_key   = False,
        );