# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
    def setup(s):
        s.PROTOCOLID = "testProtocol";
        s.addSetColumn(
            name          = "name",
            type          = "TEXT",
            notnull       = True,
            unique        = False,
            description   = "",
            default       = None,
            primary_key   = False,
        );
        s.addSetColumn(
            name          = "dsa",
            type          = "REAL",
            notnull       = False,
            unique        = False,
            description   = "",
            default       = None,
            primary_key   = False,
        );
        s.addSamColumn(
            name          = "a",
            type          = "TEXT",
            notnull       = False,
            unique        = True,
            description   = "",
            default       = None,
            primary_key   = False,
        );