# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
	def setup(s):
		s.PROTOCOLID = "VTITER";
		s.addSetColumn(
			name			= "source_file",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of raw data file",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "source_sheet",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "sheet containing raw data",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "platemap_file",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of plate map for data extraction",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "env_name",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of envelope",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "bb_name",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of backbone if applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "pseudo_live",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "PSEUDO or LIVE",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "virus_id",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "id of the virus stock tube",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "max_x",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "max final concentration of virus stock",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "fold_d",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "fold dilution of stock across series",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "reporter",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "infectivity reporter name/type",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "cell_type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "cell type inoculated",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "seed",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "cell seed density",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "well",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "well format",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "inoculation_method",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "LEAVE or SPIN inoculation types",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "read_type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "infectivity read type",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "notes",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "dilution_id",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "dilution number across series (1=max, 0=none)",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "value",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "measured infectivity value",
			default			= None,
			primary_key		= False,
		);