# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
	def setup(s):
		s.PROTOCOLID = "BNCOMBO2V2";
		s.addSetColumn(
			name			= "ENV",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name/strain of subject virus",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "PSEUDO_ID",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "tube id of virus used",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "PSEUDO_CONC",
			type			= "REAL",
			notnull			= False,
			unique			= False,
			description		= "final concentration(X) of virus",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IX",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "inhibitor titrated across x axis",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IX_MAX",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "max final concentration of inhibitor x",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IX_FOLD",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "fold dilution of inhibitor x",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IY",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "inhibitor titrated across y axis",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IY_MAX",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "max final concentration of inhibitor y",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "IY_FOLD",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "fold dilution of inhibitor y",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "SOURCE_FILE_PATH",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "path to raw data file (old)",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "SOURCE_FILE_NAME",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of raw data file",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "SOURCE_FILE_SHEET",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of sheet containing raw data where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "PLATEMAP_FILE_NAME",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of platemap file for data extraction where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "STATUS",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "NOTES",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "INOCULATED",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "1=sample contains virus, 0=no virus present",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "IX_D",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "dilution number for inhibitor x (1=max and goes up, 0 for no x)",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "IY_D",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "dilution number for inhibitor x (1=max and goes up, 0 for no x)",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "VALUE",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "measured infectivity value",
			default			= None,
			primary_key		= False,
		);
