# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
	def setup(s):
		s.PROTOCOLID = "DOSERESP";
		s.addSetColumn(
			name			= "virus_name",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of the subject virus",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "virus_tubeid",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "tube id of subject virus",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "pseudo_live",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "PSEUDO or LIVE",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "virus_conc",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "final concentration of subject virus (X)",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_name",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of effector",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_id",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "id of effector where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_tubeid",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "id of effector tube used where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_max_conc",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "max final concentration of effector in dilution series",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_conc_units",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "concentration units for effector",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "effector_fold_d",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "fold dilution of effector across series",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "preincubate_time",
			type			= "REAL",
			notnull			= False,
			unique			= False,
			description		= "effector-subject preincubation time if applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "preincubate_time_units",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "units for preincubation time",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "cell_type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "cell type used",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "seed",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "cell density on day of seeding",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "well",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "well format for inoculation",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "inoculation_method",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "LEAVE or SPIN",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "reporter",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of reporter measured",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "read_type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "reporter read well format and type",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "source_file",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of file containing original raw data",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "source_file_sheet",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "sheet containing raw data",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "project",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "project name or id",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "extra1",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "meta tag 1",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "extra2",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "meta tag 2",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "extra3",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "meta tag 3",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "notes",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "notes",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "dilution_id",
			type			= "INTEGER",
			notnull			= True,
			unique			= False,
			description		= "dilution number across series (max=1, none=0)",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "sample type",
			default			= None,
			primary_key		= False,
		);
		s.addSamColumn(
			name			= "value",
			type			= "REAL",
			notnull			= True,
			unique			= False,
			description		= "measured infectivity value",
			default			= None,
			primary_key		= False,
		);
