# pyProtocol specification generated by pyProtocol.py
from pyLabbook import pyProtocol;
class initialize(pyProtocol):
	def setup(s):
		s.PROTOCOLID = "MUTATION";
		s.addSetColumn(
			name			= "template_name",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of template plasmid/sequence",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "template_id",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "id of template plasmid tube",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "template_type",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "type of template",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "product_name",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of product",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "product_id",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "id of product",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "protocol",
			type			= "TEXT",
			notnull			= True,
			unique			= False,
			description		= "name of mutation protocol used",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "kit",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "name of mutation kit where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "kit_id",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "id of kit where applicable",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "description",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "description of the mutation or process",
			default			= None,
			primary_key		= False,
		);
		s.addSetColumn(
			name			= "notes",
			type			= "TEXT",
			notnull			= False,
			unique			= False,
			description		= "",
			default			= None,
			primary_key		= False,
		);